# Generated by Django 4.2.7 on 2023-12-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_receipt', '0003_alter_receipt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_of_purchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
